import time

class Dwarfs():
    def __init__(self):
        pass

    def greetDwarfsAtBag(self, player, room, item):
        print("")
        print("There is someone knocking on the door!")
        print("")
        time.sleep(2)
        print("--------")
        print("Bilbo: “I am so sorry to keep you waiting!” he was going to say, when he saw that it was not Gandalf at all. It was a dwarf! As soon as the door was opened, he pushed inside, just as if he had been expected.")
        time.sleep(4)
        print('')
        print("Dwalin:“Dwalin at your service!”")
        print("--------")
        time.sleep(2)
        print('')
        print("Dwalin follow Bilbo to the Dining-room")
        time.sleep(2)
        print('')
        input("Type any key to continue...")
        print('********************************************')
        print('')
        print("There came another even louder ring at the bell")
        time.sleep(2)
        print("Bilbo ran to open the door")
        time.sleep(2)
        print('')
        print("--------")
        print("Balin: “Balin at your service!“")
        time.sleep(3)
        print("--------")
        print('')
        print("Confused, Bilbo was just entering the Dining Room with Balin when he heard yet another knock on the door")
        time.sleep(3)
        print('')
        input("Type any key to continue...")
        print('********************************************')
        print('')
        print("Starting to get angry, this had to be Gandalf Bilbo thought as he opened the door")
        time.sleep(3)
        print('')
        print("--------")
        print('Kili: “Kili at your service!“')
        time.sleep(2)
        print('')
        print('Fili: “And Fili!”')
        time.sleep(1)
        print('')
        print("Dwarfs: “Dori, Nori, Ori, Oin, and Gloin at your service!“")
        time.sleep(3)
        print("")
        print("--------")
        print("")
        time.sleep(1)
        print('')
        input("Type any key to continue...")
        print('********************************************')
        print('')
        print("As Bilbo heard one more knock, very angry, and altogether bewildered and bewuthered, he opened the door.")
        time.sleep(3)
        print("")
        print("There stood Gandalf, with four more dwarfs")
        time.sleep(2)
        print("")
        print("--------")
        print("")
        print("Gandalf: “Let me introduce Bifur, Bofur, Bombur, and especially Thorin!”")
        time.sleep(2)
        print("")
        print("--------")
        print("")
        print("Very confused and not a little angry at the wizard, Bilbo lead the group to the Dining Room")
        time.sleep(2)
        print("")
        print("Gandalf: “Now we are all here! Let's eat and then begin...”")
        print("")
        room.items.append()
        input("Type any key to continue...")
        print('********************************************')
        print('')

        
